### ISSUE TITLE
Testing: download bchd, run it

### ISSUE THREAD

**Issue by readcash** [mainnet-cash/mainnet-js#2]
In order to run tests, we need to run BCHD in the background in regtest mode.

To solve this issue you need to: 

1) modify our jest tests so that before the tests suite runs, code needs to see if there's bin/bchd or bin/bchd.exe present and if not - download it automatically from the official repository and unpack.

https://github.com/gcash/bchd/releases (you can probably hardcode URLs to download 0.16.5 version, latest would be preferable, but it might be too much work for one issue)

This needs to run on Windows, Mac and Linux (so you need to download the correct binary)

Whenever the testsuite starts (via `npx jest`) we need to run BCHD into the background like this:

```
./bin/bchd --regtest --rpclisten=:18334 --rpcuser=chris --rpcpass=letmein \
  --miningaddr=bchreg:prc38tlqr6t5fk2nfcacp3w3hcljz4nj3sw247lksj
```

This starts BCHD in `regtest` mode, so you kind of have a Bitcoin Cash network of your own (without any needs for round-trips or hunting for TestNet saotshis)

2) Add a simple test that runs `./bin/bchctl --testnet -u chris -P letmein generate 1` and verifies the reply (must work on Windows, Linux, Mac). Verification should be that it's a valid json with array of one string. This will mine a block and send the reward to bchreg:prc38tlqr6t5fk2nfcacp3w3hcljz4nj3sw247lksj, we'll replace the address with address from #1, because I don't know the private key to this address (taken from the internet as an example).

3) As the test suite ends, you need to shutdown the server (shutdown should work even if jest is ctrl+c'd or crashes for some reason)

### -- $200 bounty --

The bounty is paid in BCH from the funds collected via https://github.com/mainnet-cash/mainnet-js . To claim the bounty, please do the following: if this task requires coding in TypeScript, first you need to complete the test task by sending a private message to ReadCash via [Slack link here](https://github.com/mainnet-cash/project#where-are-we); 2) after you have completed test task once, tell that you are working on this task and how long it is going to take (if that time expires, anyone else is free to take the task); 3) send a Pull Request or publish the solution here as described in the issue. Good luck! If you think that bounty is way too small, please notify me about it and we can discuss. A bounty will be paid via the chaintip bot.

**Comment by 2qx** [comment]
@readcash , This seems like a candidate for docker-compose (can be deployed to desktop/k8s) with waiting for dependent services.  zquest has a docker image published for bchd also.  

Since it would be nice to keep everything in one language, may the test be written as an XHR to the bchd service? and then a second one to verify that the block has been mined?

The configuration is about yea big:

```
version: '3'
services:
  service:
    build: .
    depends_on:
      - "bchd-regtest"
    command: ["npx", "jest"]
  bchd-regtest:
    image: "zquestz/bchd:latest"
    entrypoint: ["bchd", "--regtest", "--addrindex", "--txindex", "--rpcuser=alice", "--rpcpass=justTesting", "--miningaddr=$REGTEST_ADDRESS", "-b", "/data", "-C", "/data/bchd.conf"]
```
